/*
 * This file is generated by jOOQ.
 */
package hst.peter.jooq.codegen.tables;


import hst.peter.jooq.codegen.Demodb;
import hst.peter.jooq.codegen.Indexes;
import hst.peter.jooq.codegen.Keys;
import hst.peter.jooq.codegen.tables.records.TStudentRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TStudent extends TableImpl<TStudentRecord> {

    private static final long serialVersionUID = -789013310;

    /**
     * The reference instance of <code>demodb.t_student</code>
     */
    public static final TStudent T_STUDENT = new TStudent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TStudentRecord> getRecordType() {
        return TStudentRecord.class;
    }

    /**
     * The column <code>demodb.t_student.id</code>.
     */
    public final TableField<TStudentRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>demodb.t_student.name</code>.
     */
    public final TableField<TStudentRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>demodb.t_student.age</code>.
     */
    public final TableField<TStudentRecord, Integer> AGE = createField(DSL.name("age"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>demodb.t_student</code> table reference
     */
    public TStudent() {
        this(DSL.name("t_student"), null);
    }

    /**
     * Create an aliased <code>demodb.t_student</code> table reference
     */
    public TStudent(String alias) {
        this(DSL.name(alias), T_STUDENT);
    }

    /**
     * Create an aliased <code>demodb.t_student</code> table reference
     */
    public TStudent(Name alias) {
        this(alias, T_STUDENT);
    }

    private TStudent(Name alias, Table<TStudentRecord> aliased) {
        this(alias, aliased, null);
    }

    private TStudent(Name alias, Table<TStudentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TStudent(Table<O> child, ForeignKey<O, TStudentRecord> key) {
        super(child, key, T_STUDENT);
    }

    @Override
    public Schema getSchema() {
        return Demodb.DEMODB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_STUDENT_PRIMARY);
    }

    @Override
    public Identity<TStudentRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_STUDENT;
    }

    @Override
    public UniqueKey<TStudentRecord> getPrimaryKey() {
        return Keys.KEY_T_STUDENT_PRIMARY;
    }

    @Override
    public List<UniqueKey<TStudentRecord>> getKeys() {
        return Arrays.<UniqueKey<TStudentRecord>>asList(Keys.KEY_T_STUDENT_PRIMARY);
    }

    @Override
    public TStudent as(String alias) {
        return new TStudent(DSL.name(alias), this);
    }

    @Override
    public TStudent as(Name alias) {
        return new TStudent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TStudent rename(String name) {
        return new TStudent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TStudent rename(Name name) {
        return new TStudent(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
