/*
 * This file is generated by jOOQ.
 */
package hst.peter.jooq.codegen.tables.records;


import hst.peter.jooq.codegen.tables.T1;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T1Record extends TableRecordImpl<T1Record> implements Record2<Integer, String> {

    private static final long serialVersionUID = 2058017722;

    /**
     * Setter for <code>demodb.t1.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>demodb.t1.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>demodb.t1.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>demodb.t1.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return T1.T1.ID;
    }

    @Override
    public Field<String> field2() {
        return T1.T1.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public T1Record value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public T1Record value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public T1Record values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached T1Record
     */
    public T1Record() {
        super(T1.T1);
    }

    /**
     * Create a detached, initialised T1Record
     */
    public T1Record(Integer id, String name) {
        super(T1.T1);

        set(0, id);
        set(1, name);
    }
}
