/*
 * This file is generated by jOOQ.
 */
package hst.peter.jooq.codegen;


import hst.peter.jooq.codegen.tables.Author;
import hst.peter.jooq.codegen.tables.Book;
import hst.peter.jooq.codegen.tables.BookStore;
import hst.peter.jooq.codegen.tables.BookToBookStore;
import hst.peter.jooq.codegen.tables.Language;
import hst.peter.jooq.codegen.tables.T1;
import hst.peter.jooq.codegen.tables.TStudent;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in demodb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>demodb.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>demodb.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>demodb.book_store</code>.
     */
    public static final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>demodb.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>demodb.language</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>demodb.t1</code>.
     */
    public static final T1 T1 = hst.peter.jooq.codegen.tables.T1.T1;

    /**
     * The table <code>demodb.t_student</code>.
     */
    public static final TStudent T_STUDENT = TStudent.T_STUDENT;
}
